phrases_original = [
    'A blessing in disguise',
    'A dime a dozen',
    'Beat around the bush',
    'Better late than never',
    'Bite the bullet',
    'Break a leg',
    'Call it a day',
    'Cut me some slack',
    'Get your act together',
    'Back to the drawing board',
    'Hang in there',
    'Hit the sack',
    'On the ball',
    'Speak of the devil',
    'So far so good',
    'Pull yourself together',
    'The best of both worlds',
    'Time flies when you are having fun',
    'Under the weather',
    'You can say that again',
    'Your guess is as good as mine',
    'A bird in the hand is worth two in the bush',
    'A penny for your thoughts',
    'A perfect storm',
    'A penny saved is a penny earned',
    'Barking up the wrong tree',
    'Birds of a feather flock together',
    'By the skin of your teeth',
    'At the drop of a hat',
    'Every cloud has a silver lining',
    'A taste of your own medicine',
    'A wild goose chase',
    'Good things come to those who wait',
    'Hit the nail on the head',
    'Ignorance is bliss',
    'It takes one to know one',
    'A piece of cake',
    'Kill two birds with one stone',
    'Let the cat out of the bag',
    'Live and learn',
    'Look before you leap',
    'On thin ice',
    'Once in a blue moon',
    'Slow and steady wins the race',
    'Spill the beans',
    'Take it with a grain of salt',
    'The devil is in the details',
    'The early bird gets the worm',
    'The elephant in the room',
    'The whole nine yards',
    'There are other fish in the sea',
    'Throw caution to the wind',
    'You can have your cake and eat it too',
    'An Apple a day keeps the doctor away',
    'Every dog has his day',
    'Fit as a fiddle',
    'Fortune favours the bold',
    'It is always darkest before the dawn',
    'Jump on the bandwagon',
]